-- 1. Para habilitar extensión espacial para mapas (obligatorio para coordenadas geográficas)
CREATE EXTENSION IF NOT EXISTS postgis SCHEMA public;

-- 1.1 Crear esquemas según arquitectura
CREATE SCHEMA IF NOT EXISTS rtc_auth;
CREATE SCHEMA IF NOT EXISTS category;
CREATE SCHEMA IF NOT EXISTS report;
CREATE SCHEMA IF NOT EXISTS "user";
CREATE SCHEMA IF NOT EXISTS optimization;

-- 2. Creación de Tablas Principales de Reporta Tu Calle

CREATE TABLE rtc_auth.auth_accounts (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(150) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    CONSTRAINT auth_accounts_pkey PRIMARY KEY (id),
    CONSTRAINT uk_auth_accounts_email UNIQUE (email),
    CONSTRAINT auth_accounts_role_check CHECK (((role)::text = ANY ((ARRAY['CITIZEN'::character varying, 'SUPERVISOR'::character varying, 'ADMIN'::character varying])::text[])))
);

CREATE TABLE category.categories (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    marker_color character varying(7),
    name character varying(100) NOT NULL,
    algorithm_type character varying(50) NOT NULL,
    updated_at timestamp without time zone,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT uk_categories_name UNIQUE (name)
);

CREATE TABLE "user".user_profiles (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    phone character varying(20),
    CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT uk_user_profiles_account_id UNIQUE (account_id)
);

CREATE TABLE report.reports (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    category_id bigint NOT NULL,
    citizen_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text NOT NULL,
    image_url character varying(500),
    location public.geometry(Point,4326) NOT NULL,
    report_count integer NOT NULL,
    status character varying(20) NOT NULL,
    title character varying(150) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT reports_pkey PRIMARY KEY (id),
    CONSTRAINT reports_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_PROGRESS'::character varying, 'RESOLVED'::character varying, 'REJECTED'::character varying])::text[])))
);

CREATE TABLE report.report_endorsements (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    citizen_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    report_id bigint NOT NULL,
    CONSTRAINT report_endorsements_pkey PRIMARY KEY (id)
);