CREATE TABLE optimization.route_history (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    supervisor_id bigint NOT NULL,
    category_id bigint NOT NULL,
    route_data_json text NOT NULL,
    total_distance_km double precision NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT route_history_pkey PRIMARY KEY (id),
    CONSTRAINT route_history_status_check CHECK (((status)::text = ANY ((ARRAY['SAVED'::character varying, 'COMPLETED'::character varying, 'DISCARDED'::character varying])::text[])))
);
