spring:
  application:
    name: reporta-tu-calle-api
  output:
    ansi:
      enabled: always

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO
    com.reportatucalle: DEBUG
